### ISSUE TITLE
headreco: Gmsh failed meshing

### ISSUE THREAD

**Issue by legendleaf** [simnibs/simnibs#71]
Dear SimNIBS experts，

Thank you for providing such powerful software！
I have some problems when using the command "headreco".
I performed headreco -all sampleYX YX_T1.nii YX_T2.nii
sampleYX is the ID of the current subject. The next two are T1 and T2.
The reported bugs are as follows:
Gmsh exit code: 2

Gmsh failed meshing one or more surfaces. Trying Delaunay meshing

Gmsh exit code: 2
Traceback (most recent call last):
  File "/Users/feng/Applications/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/cli/headreco.py", line 13, in <module>
    main()
  File "/Users/feng/Applications/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/cli/headreco.py", line 10, in main
    headmodel(sys.argv)
  File "/Users/feng/Applications/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/msh/headreco.py", line 693, in headmodel
    vmsh = make_volume_mesh(args.subject_id, surfaces, subject_dir, args.keep_air)
  File "/Users/feng/Applications/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/msh/headreco.py", line 1941, in make_volume_mesh
    raise RuntimeError("Gmsh failed meshing one or more surfaces in {} attempts.".format(attempts))
RuntimeError: Gmsh failed meshing one or more surfaces in 3 attempts.
(base) FengdeMacBook-Pro:sampleYX feng$

In addition, I also tried it with ernie data and got the same error.
Referring to the question answered in the previous issue question, I tried headreco all -v 1 sampleYX YX_T1.nii YX_T2.nii, and got the same above error.

I have sent a screenshot of the bug report to support@simnibs.org
Thank you for any help!
Zaki Feng
<img width="1440" alt="Bug_reportwith_headreco" src="https://user-images.githubusercontent.com/43163606/146889911-a8f8abd1-7076-46c2-bbad-2355b25b5025.png">

**Comment by legendleaf** [comment]
In addition, I just want the head model information but not the surface or deep cerebral cortex information. Can I use the following code to extract it?

%%   Get a head model without cortical information
clear all;
close all;
clc;
fn = 'ernie.msh';
m=mesh_load_gmsh4(fn);
trep = triangulation(double(m.tetrahedra), m.nodes(:,1),m.nodes(:,2),m.nodes(:,3));
m.triangles=freeBoundary(trep);
m.triangle_regions=1002*ones(length(m.triangles),1);
fn = 'headwithoutsurface_ernie.msh';
mesh_save_gmsh4(m, fn)

Thank you for any help!
Zaki Feng

**Comment by ulloaa** [comment]
Hi,

We are also getting this same error using headreco on the ernie dataset (see error below). Is this a bug, and if so, is there a workaround?

-------------------------------------------
========================================================================
GENERATING VOLUME MESH
========================================================================

Creating .geo file
Creating volume mesh using Gmsh
========================================================================
Gmsh exit code: 1

Gmsh failed meshing one or more surfaces. Doing uniform remeshing and retrying
Remeshing wm.stl
Remeshing gm.stl
Remeshing csf.stl
Remeshing bone.stl
Remeshing skin.stl
Remeshing eyes.stl
Remeshing cavities.stl
Remeshing air_outer_decoupled.stl
Remeshing ventricles.stl
Decoupling
Decoupling ventricles from GM
Decoupling WM from ventricles
Decoupling GM from WM

Gmsh exit code: 1

Gmsh failed meshing one or more surfaces. Trying Delaunay meshing

Gmsh exit code: 1
Traceback (most recent call last):
File "/bin/headreco", line 8, in <module>
sys.exit(main())
File "/python3.7/site-packages/simnibs/cli/headreco.py", line 10, in main
headmodel(sys.argv)
File "/python3.7/site-packages/simnibs/msh/headreco.py", line 693, in headmodel
vmsh = make_volume_mesh(args.subject_id, surfaces, subject_dir, args.keep_air)
File "/python3.7/site-packages/simnibs/msh/headreco.py", line 1941, in make_volume_mesh
raise RuntimeError("Gmsh failed meshing one or more surfaces in {} attempts.".format(attempts))
RuntimeError: Gmsh failed meshing one or more surfaces in 3 attempts.
-------------------------------------------------------------

**Comment by legendleaf** [comment]
Not yet.
I tried flag -v or --no-cat. The same error returned.
Another macOS re-installed SimNIBS returned the same error.

**Comment by sdsmet** [comment]
Hi all, 

Experiencing the same issues here with the Ernie example dataset; 

=======================
GENERATING VOLUME MESH
=======================

Creating .geo file
Creating volume mesh using Gmsh
===========================================
Gmsh exit code: 2

Gmsh failed meshing one or more surfaces. Doing uniform remeshing and retrying
Remeshing wm.stl
Remeshing gm.stl
Remeshing csf.stl
Remeshing bone.stl
Remeshing skin.stl
Remeshing eyes.stl
Remeshing cavities.stl
Remeshing air_outer_decoupled.stl
Remeshing ventricles.stl
Decoupling
Decoupling ventricles from GM
Decoupling WM from ventricles
Decoupling GM from WM

Gmsh exit code: 2

Gmsh failed meshing one or more surfaces. Trying Delaunay meshing

Gmsh exit code: 2
Traceback (most recent call last):
  File "/Users/stefaniedesmet/Applications/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/cli/headreco.py", line 13, in <module>
    main()
  File "/Users/stefaniedesmet/Applications/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/cli/headreco.py", line 10, in main
    headmodel(sys.argv)
  File "/Users/stefaniedesmet/Applications/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/msh/headreco.py", line 693, in headmodel
    vmsh = make_volume_mesh(args.subject_id, surfaces, subject_dir, args.keep_air)
  File "/Users/stefaniedesmet/Applications/SimNIBS-3.2/simnibs_env/lib/python3.7/site-packages/simnibs/msh/headreco.py", line 1941, in make_volume_mesh
    raise RuntimeError("Gmsh failed meshing one or more surfaces in {} attempts.".format(attempts))
RuntimeError: Gmsh failed meshing one or more surfaces in 3 attempts.

I am running this on a MacBook Pro (M1 chip) macOS Monterey. Tried running it yesterday on a friend her Dell XPS - windows 10 and no error.. Are you also running SIMNIBS on Macs with M1 chips?

see also this comment from the Changelog 3.2.2; "SimNIBS is so far not tested on Macs with Apple Silicon, and is likely to give errors on those machines"

**Comment by ulloaa** [comment]
We are getting the error on Linux using version 3.2.5.

**Comment by ulloaa** [comment]
We tried every single version prior to 3.2.5 and got the same error in each version except with 3.0

**Comment by oulap** [comment]
Hi,

Sorry have completely missed this one. We haven't tested SimNIBS on the new M1 macs yet, so no guarantees there as the website states.

I tried re-running ernie with the latest SimNIBS version on Ubuntu 20.04 and the seems to work.

Please send your headreco_log.htmls to support@simnibs.org, so we can have a closer look.

**Comment by legendleaf** [comment]
Dear experts,


Sorry for the late reply. My current&nbsp;SimNIBS version&nbsp;is&nbsp;3.2.5.
I uploaded the headreco_log.htmls.


Thank you for any help!
Zaki




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "simnibs/simnibs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月9日(星期三) 晚上9:53
***@***.***&gt;;
抄送:&nbsp;"子健 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [simnibs/simnibs] headreco: Gmsh failed meshing (Issue #71)





 
Hi,
 
Sorry have completely missed this one. We haven't tested SimNIBS on the new M1 macs yet, so no guarantees there as the website states.
 
I tried re-running ernie with the latest SimNIBS version on Ubuntu 20.04 and the seems to work.
 
Please send your headreco_log.htmls to ***@***.***, so we can have a closer look.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by oulap** [comment]
Thanks, we're looking into this but seems like a gmsh issue. We have now also a M1 mac so we can test on that as well.

**Comment by legendleaf** [comment]
Thank you！Looking forward to your good news.
Best,
Zaki

---Original---
From: ***@***.***&gt;
Date: Fri, Feb 18, 2022 19:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [simnibs/simnibs] headreco: Gmsh failed meshing (Issue #71)




 
Thanks, we're looking into this but seems like a gmsh issue. We have now also a M1 mac so we can test on that as well.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by oulap** [comment]
The problem with gmsh on Macs should be fixed in the new release. Give it try and let us know if it works.

**Comment by jacorvar** [comment]
This issue still persists on CentOS 7.9 with Simnibs 3.2.6. I've tried downloading the installer and also using conda.

**Comment by oulap** [comment]
I think we managed to fix this in headreco (hopefully). In version 4 this should not be an issue as the meshing was completely changed.
